### ISSUE TITLE
Saving xlsx file discards existing charts

### ISSUE THREAD

**Issue by nick133** [mashingan/excelin#1]
Hi,
```
let xl = readExcel("calc.xlsx")
let sheet = xl.getSheet("Calc")
sheet.row(1)["A"] = "hello"
xl.writeFile("calc-out.xlsx")
```
There was pie chart in different sheet in _calc.xlsx_ and after running this code that chart was gone in _calc-out.xlsx_. I wonder is it a bug or saving a charts/diagrams is unsupported yet?

**Comment by mashingan** [comment]
Strictly speaking chart/drawing/diagram is not supported yet, but `readExcel` missed out reading the relations file hence it's bug.  

Feel free to re-open if it's still problem.
