### ISSUE TITLE
Embedded image is missing after saving

### ISSUE THREAD

**Issue by nick133** [mashingan/excelin#2]
#1 it seems this works as expected now, but other thing is showing up, here's how it looks like after and before saving:

![20220505_00h37m58s_grim](https://user-images.githubusercontent.com/1276245/166831125-995f62bf-f3fb-438e-931a-cfc84661c5ae.png)

btw, all this happens under linux/libreoffice calc

**Comment by mashingan** [comment]
Alright, this is definitely the same root cause with #1 . We'll look at it later. Thanks for reporting.

**Comment by mashingan** [comment]
Feel free to re-open if the problem persists.

**Comment by nick133** [comment]
works nice so far, thanks!
