### ISSUE TITLE
error when parsing simple excel file

### ISSUE THREAD

**Issue by hamidb80** [mashingan/excelin#5]
hey, just installed your library and code this:

```nim
import excelin
let xf = readExcel "./sample.xlsx"
```

result:
```
Traceback (most recent call last)
<USER>\Documents\dads_project\test\play.nim(2) play
<USER>\.nimble\pkgs\excelin-0.4.10\excelin.nim(147) readExcel
<USER>\.nimble\pkgs\excelin-0.4.10\excelin.nim(36) addSharedStrings
<USER>\.choosenim\toolchains\nim-#devel\lib\pure\xmltree.nim(357) len
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

the excel file is so simple, only has 1 row & column:
![image](https://user-images.githubusercontent.com/33871336/177771680-ba6ea6ec-8617-4f9a-8240-91f82614e169.png)

file [generated using WPS Office on windows ]:
[sample.xlsx](https://github.com/mashingan/excelin/files/9063439/sample.xlsx)

nim version: 1.7.1

**Comment by mashingan** [comment]
The issue is caused by WPS doesn't include/specify path for the workbook relation file in content xml. Hence Excelin missed reading it.  
Should already fixed but if the problem persists, please comment.
